export default  [
  {
    name: 'ABC Shirts', 
    imageURL: require('../../asset/image/art/1000/abcd-shirts-1000.png'),
    description: 'A person painting the alphabet on t-shirts.',
    isDouble: false,
  },
  {
    name: 'Adult', 
    imageURL: require('../../asset/image/art/1000/adult-1000.png'),
    description: '"I\'m getting my life together"',
    isDouble: false,
  },
  {
    name: 'Bad Luck', 
    imageURL: require('../../asset/image/art/1000/bad-luck-1000.png'),
    description: 'A person surounded by bad luck.',
    isDouble: false,
  },
  {
    name: 'Big Brother', 
    imageURL: require('../../asset/image/art/1000/big-bro-1000.png'),
    description: 'Just an ordinary day with lots of survailance.',
    isDouble: false,
  },
  {
    name: 'Bus Stop', 
    imageURL: require('../../asset/image/art/1000/bus-stop-1000.png'),
    description: 'Waiting for the bus.',
    isDouble: false,
  },
  {
    name: 'Cookout', 
    imageURL: require('../../asset/image/art/1000/cook-out-1000.png'),
    description: 'Grilling in the woods.',
    isDouble: false,
  },
  {
    name: 'Our Queen',
    imageURL: require('../../asset/image/art/1000/forest-queen-1000.png'),
    description: 'The Mother, Our Queen',
    isDouble: false,
  },
  {
    name: 'Fortune',
    imageURL: require('../../asset/image/art/1000/fortune-et-1000.png'),
    description: 'Observing a fortune teller at work.',
    isDouble: false,
  },
  {
    name: 'Grimlin Garden',
    imageURL: require('../../asset/image/art/1000/grimlin-garden-1000.png'),
    description: 'Couple of grimlins in the garden',
    isDouble: false,
  },
  {
    name: 'Grocery Fashion',
    imageURL: require('../../asset/image/art/1000/grocey-fashion-1000.png'),
    description: 'Coupole of good lookin kid in the produce section.',
    isDouble: false,
  },
  {
    name: 'Guuh',
    imageURL: require('../../asset/image/art/1000/guuh-1000.png'),
    description: 'Guuh',
    isDouble: false,
  },
  {
    name: 'Hey Bud',
    imageURL: require('../../asset/image/art/1000/hey-bud-1000.png'),
    description: 'Dog on a boat, Boy on a dock.',
    isDouble: false,
  },
  {
    name: 'Internet Cowboys',
    imageURL: require('../../asset/image/art/1000/internet-cowboys-1000.png'),
    description: 'Internet cowboys be like "Don\'t forget to like and subscribe yall".',
    isDouble: false,
  },
  {
    name: 'Jello Theater',
    imageURL: require('../../asset/image/art/1000/jello-theater-1000.png'),
    description: 'A Space Jello Movie.',
    isDouble: false,
  },
  {
    name: 'Jester',
    imageURL: require('../../asset/image/art/1000/jester-0-1000.png'),
    description: 'Just a Jester.',
    isDouble: false,
  },
  {
    name: 'Jester',
    imageURL: require('../../asset/image/art/1000/jester-1-1000.png'),
    description: 'Just a Jester.',
    isDouble: false,
  },
  {
    name: 'Laundry',
    imageURL: require('../../asset/image/art/1000/laundry-1000.png'), 
    description: 'Doing laundry in a laundromatt.',
    isDouble: false,
  },
  {
    name: 'Strolling through the neighborhood',
    imageURL: require('../../asset/image/art/1000/mail-stroll-1000.png'), 
    description: 'A girl strolling through the neighborhood.',
    isDouble: false,
  },
  {
    name: 'Moral Support',
    imageURL: require('../../asset/image/art/1000/moral-support-1000.png'), 
    description: 'A friend "being there" for a friend.',
    isDouble: false,
  },
  {
    name: 'Mountain Lunch',
    imageURL: require('../../asset/image/art/1000/mountain-lunch-1000.png'), 
    description: 'Lunch in the mountains with a cat.',
    isDouble: false,
  },
  {
    name: 'Night Stroll',
    imageURL: require('../../asset/image/art/1000/night-stroll-1000.png'), 
    description: 'Wonderin in the dark with a flashlight',
    isDouble: false,
  },
  {
    name: 'Photo Shoot',
    imageURL: require('../../asset/image/art/1000/photo-shoot-1000.png'), 
    description: 'A photo shoot.',
    isDouble: false,
  },
  {
    name: 'Pizza Maker',
    imageURL: require('../../asset/image/art/1000/pizza-1000.png'), 
    description: 'Making a Pizza.',
    isDouble: false,
  },
  {
    name: 'Say Cheese',
    imageURL: require('../../asset/image/art/1000/say-cheese-1000.png'), 
    description: 'Saping a candid photo in the mountians.',
    isDouble: false,
  },
  {
    name: 'See yall later',
    imageURL: require('../../asset/image/art/1000/seeyalater-1000.png'), 
    description: 'They are running away.',
    isDouble: false,
  },
  {
    name: 'Sound Smith',
    imageURL: require('../../asset/image/art/1000/sound-smith-1000.png'), 
    description: 'A sound-smith doing what a sound-smith do.',
    isDouble: false,
  },
  {
    name: 'Sunday',
    imageURL: require('../../asset/image/art/1000/sunday-1000.png'), 
    description: 'Sunday chorz.',
    isDouble: false,
  },
  {
    name: 'Tennis',
    imageURL: require('../../asset/image/art/1000/tennis-1000.png'), 
    description: 'Slamming a tennis ball.',
    isDouble: false,
  },
  {
    name: 'We love cat',
    imageURL: require('../../asset/image/art/1000/we-love-cat-1000.png'), 
    description: 'Two people love the cat.',
    isDouble: false,
  },
]
