export default  [
  {
    name: 'ABC Shirts', 
    imageURL: require('../../asset/image/art/1000/abcd-shirts-1000.png'),
    description: 'A person painting the alphabet on t-shirts.',
    isDouble: false,
  },
  {
    name: 'Adult', 
    imageURL: require('../../asset/image/art/1000/adult-1000.png'),
    description: '"I\'m getting my life together"',
    isDouble: false,
  },
  //{
    //name: 'Bad Luck', 
    //imageURL: require('../../asset/image/art/bad-luck.png'),
    //description: 'A person surounded by bad luck.',
    //isDouble: false,
  //},
  //{
    //name: 'Big Brother', 
    //imageURL: require('../../asset/image/art/big-bro.png'),
    //description: 'Just an ordinary day with lots of survailance.',
    //isDouble: false,
  //},
  //{
    //name: 'Bus Stop', 
    //imageURL: require('../../asset/image/art/bus-stop.png'),
    //description: 'Waiting for the bus.',
    //isDouble: false,
  //},
  //{
    //name: 'Cookout', 
    //imageURL: require('../../asset/image/art/cook-out.png'),
    //description: 'Grilling in the woods.',
    //isDouble: false,
  //},
  //{
    //name: 'Our Queen',
    //imageURL: require('../../asset/image/art/forest-queen.png'),
    //description: 'The Mother, Our Queen',
    //isDouble: false,
  //},
  //{
    //name: 'Fortune',
    //imageURL: require('../../asset/image/art/fortune-et.png'),
    //description: 'Observing a fortune teller at work.',
    //isDouble: false,
  //},
  //{
    //name: 'Grimlin Garden',
    //imageURL: require('../../asset/image/art/grimlin-garden.png'),
    //description: 'Couple of grimlins in the garden',
    //isDouble: false,
  //},
  //{
    //name: 'Grocery Fashion',
    //imageURL: require('../../asset/image/art/grocey-fashion.png'),
    //description: 'Coupole of good lookin kid in the produce section.',
    //isDouble: false,
  //},
  //{
    //name: 'Guuh',
    //imageURL: require('../../asset/image/art/guuh.png'),
    //description: 'Guuh',
    //isDouble: false,
  //},
  //{
    //name: 'Hey Bud',
    //imageURL: require('../../asset/image/art/hey-bud.png'),
    //description: 'Dog on a boat, Boy on a dock.',
    //isDouble: false,
  //},
  //{
    //name: 'Internet Cowboys',
    //imageURL: require('../../asset/image/art/internet-cowboys.png'),
    //description: 'Internet cowboys be like "Don\'t forget to like and subscribe yall".',
    //isDouble: false,
  //},
  //{
    //name: 'Jello Theater',
    //imageURL: require('../../asset/image/art/jello-theater.png'),
    //description: 'A Space Jello Movie.',
    //isDouble: false,
  //},
  //{
    //name: 'Jester',
    //imageURL: require('../../asset/image/art/jester-0.png'),
    //description: 'Just a Jester.',
    //isDouble: false,
  //},
  //{
    //name: 'Jester',
    //imageURL: require('../../asset/image/art/jester-1.png'),
    //description: 'Just a Jester.',
    //isDouble: false,
  //},
  //{
    //name: 'Laundry',
    //imageURL: require('../../asset/image/art/laundry.png'), 
    //description: 'Doing laundry in a laundromatt.',
    //isDouble: false,
  //},
  //{
    //name: 'Strolling through the neighborhood',
    //imageURL: require('../../asset/image/art/mail-stroll.png'), 
    //description: 'A girl strolling through the neighborhood.',
    //isDouble: false,
  //},
  //{
    //name: 'Moral Support',
    //imageURL: require('../../asset/image/art/moral-support.png'), 
    //description: 'A friend "being there" for a friend.',
    //isDouble: false,
  //},
  //{
    //name: 'Mountain Lunch',
    //imageURL: require('../../asset/image/art/mountain-lunch.png'), 
    //description: 'Lunch in the mountains with a cat.',
    //isDouble: false,
  //},
  //{
    //name: 'Night Stroll',
    //imageURL: require('../../asset/image/art/night-stroll.png'), 
    //description: 'Wonderin in the dark with a flashlight',
    //isDouble: false,
  //},
  //{
    //name: 'Photo Shoot',
    //imageURL: require('../../asset/image/art/photo-shoot.png'), 
    //description: 'A photo shoot.',
    //isDouble: false,
  //},
  //{
    //name: 'Pizza Maker',
    //imageURL: require('../../asset/image/art/pizza.png'), 
    //description: 'Making a Pizza.',
    //isDouble: false,
  //},
  //{
    //name: 'Say Cheese',
    //imageURL: require('../../asset/image/art/say-cheese.png'), 
    //description: 'Saping a candid photo in the mountians.',
    //isDouble: false,
  //},
  //{
    //name: 'See yall later',
    //imageURL: require('../../asset/image/art/seeyalater.png'), 
    //description: 'They are running away.',
    //isDouble: false,
  //},
  //{
    //name: 'Sound Smith',
    //imageURL: require('../../asset/image/art/sound-smith.png'), 
    //description: 'A sound-smith doing what a sound-smith do.',
    //isDouble: false,
  //},
  //{
    //name: 'Sunday',
    //imageURL: require('../../asset/image/art/sunday.png'), 
    //description: 'Sunday chorz.',
    //isDouble: false,
  //},
  //{
    //name: 'Tennis',
    //imageURL: require('../../asset/image/art/tennis.png'), 
    //description: 'Slamming a tennis ball.',
    //isDouble: false,
  //},
  //{
    //name: 'We love cat',
    //imageURL: require('../../asset/image/art/we-love-cat.png'), 
    //description: 'Two people love the cat.',
    //isDouble: false,
  //},
]
